//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championship
    {
        public Nullable<System.Guid> id { get; set; }
        public string name { get; set; }
        public System.Guid seasonId { get; set; }
    
        public virtual Season Season { get; set; }
    }
}
