//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public System.Guid id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public string nationality { get; set; }
        public string position { get; set; }
        public string previousClubs { get; set; }
    }
}
