//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public System.Guid id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string position { get; set; }
        public Nullable<System.Guid> teamId { get; set; }
        public Nullable<System.Guid> seasonId { get; set; }
    }
}
