//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid id { get; set; }
        public string alias { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public Nullable<System.Guid> ownerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
